# https://dev.azure.com/home-assistant

trigger:
  batch: true
  branches:
    include:
      - dev
  tags:
    include:
      - "*"
  paths:
    include:
    - supervisor/*
    - rootfs/*
    - requirements.txt
    - setup.py
    - Dockerfile
    - build.json
pr: none
variables:
  - name: versionBuilder
    value: "7.2.0"
  - group: docker
  - group: github
resources:
  repositories:
    - repository: azure
      type: github
      name: "home-assistant/ci-azure"
      endpoint: "home-assistant"

stages:
  - stage: "Validate"
    jobs:
      - template: templates/azp-job-version.yaml@azure
        parameters:
          ignoreDev: true

  - stage: "Build"
    jobs:
      - job: "ReleaseDocker"
        timeoutInMinutes: 240
        pool:
          vmImage: "ubuntu-latest"
        strategy:
          maxParallel: 5
          matrix:
            amd64:
              buildArch: "amd64"
            i386:
              buildArch: "i386"
            armhf:
              buildArch: "armhf"
            armv7:
              buildArch: "armv7"
            aarch64:
              buildArch: "aarch64"
        steps:
          - template: templates/azp-step-su-version.yaml@azure
          - template: templates/azp-step-build-generic.yaml@azure
            parameters:
              buildArch: $(buildArch)
              buildVersion: $(supervisorRelease)

  - stage: "Publish"
    jobs:
      - job: "ReleaseHassio"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - template: templates/azp-step-su-version.yaml@azure
          - template: templates/azp-step-version-push.yaml@azure
            parameters:
              jsonTag: supervisor
              commitName: Supervisor
              buildVersion: $(supervisorRelease)
