# https://dev.azure.com/home-assistant

trigger:
  batch: true
  branches:
    include:
      - dev
  tags:
    include:
      - "*"
  paths:
    include:
    - supervisor/*
    - rootfs/*
    - requirements.txt
    - setup.py
    - Dockerfile
    - build.json
pr: none
variables:
  - name: versionBuilder
    value: "7.2.0"
  - group: docker
resources:
  repositories:
    - repository: azure
      type: github
      name: "home-assistant/ci-azure"
      endpoint: "home-assistant"

stages:
  - stage: "Validate"
    jobs:
      - template: templates/azp-job-version.yaml@azure
        parameters:
          ignoreDev: true

  - stage: "Build"
    jobs:
      - job: "ReleaseDocker"
        timeoutInMinutes: 240
        pool:
          vmImage: "ubuntu-latest"
        strategy:
          maxParallel: 5
          matrix:
            amd64:
              buildArch: "amd64"
            i386:
              buildArch: "i386"
            armhf:
              buildArch: "armhf"
            armv7:
              buildArch: "armv7"
            aarch64:
              buildArch: "aarch64"
        steps:
          - template: templates/azp-step-su-version.yaml@azure
          - script: |
              docker login -u $(dockerUser) -p $(dockerPassword)
            displayName: "Docker hub login"
          - script: docker pull homeassistant/amd64-builder:$(versionBuilder)
            displayName: "Install Builder"
          - script: |
              sudo docker run --rm --privileged \
                  -v ~/.docker:/root/.docker \
                  -v /run/docker.sock:/run/docker.sock:rw \
                  -v $(pwd):/data:ro \
                  homeassistant/amd64-builder:$(versionBuilder) \
                    --generic $(supervisorRelease) "--$(buildArch)" -t /data
            displayName: "Build Release"

  - stage: "Publish"
    jobs:
      - job: "ReleaseHassio"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - template: templates/azp-step-su-version.yaml@azure
          - template: templates/azp-step-git-init.yaml@azure
          - script: |
              sudo apt-get install -y --no-install-recommends \
                jq
            displayName: "Install requirements"
          - script: |
              set -e

              version="$(supervisorRelease)"

              git clone https://github.com/home-assistant/hassio-version
              cd hassio-version

              dev_version="$(jq --raw-output '.supervisor' dev.json)"
              beta_version="$(jq --raw-output '.supervisor' beta.json)"

              if [[ "$version" =~ dev ]]; then
                sed -i "s|\"supervisor\": \"$dev_version\"|\"supervisor\": \"$version\"|g" dev.json
              else
                sed -i "s|\"supervisor\": \"$beta_version\"|\"supervisor\": \"$version\"|g" beta.json
              fi

              git commit -am "Bump Supervisor $version"
              git push
            displayName: "Update version files"
